const actionTypes = {
    // employment Information
    SET_EMP_ID: "SET_EMP_ID",
    SET_EMP_NAME: "SET_EMP_NAME",
    SET_EMP_DESIGNATION: "SET_EMP_DESIGNATION",
    SET_EMP_EMAIL: "SET_EMP_EMAIL",
    SET_COMP_NAME: "SET_COMP_NAME",
    SET_COMP_ADDRESS: "SET_COMP_ADDRESS",
    SET_EMP_CONTACT_NO: "SET_EMP_CONTACT_NO",

    SET_EMP_ID_ERROR: "SET_EMP_ID_ERROR",
    SET_EMP_NAME_ERROR: "SET_EMP_NAME_ERROR",
    SET_EMP_DESIGNATION_ERROR: "SET_EMP_DESIGNATION_ERROR",
    SET_EMP_EMAIL_ERROR: "SET_EMP_EMAIL_ERROR",
    SET_COMP_NAME_ERROR: "SET_COMP_NAME_ERROR",
    SET_COMP_ADDRESS_ERROR: "SET_COMP_ADDRESS_ERROR",
    SET_EMP_CONTACT_NO_ERROR: "SET_EMP_CONTACT_NOERROR",

    // personal inofrmation
    SET_GENDER: "SET_GENDER",
    SET_DOB: "SET_DOB",
    SET_MARITAL_STATUS: "SET_MARITAL_STATUS",
    SET_HOME_ADDRESS: "SET_HOME_ADDRESS",
    SET_HOME_CONTACT_NO: "SET_HOME_CONTACT_NO",

    SET_GENDER_ERROR: "SET_GENDER_ERROR",
    SET_DOB_ERROR: "SET_DOB_ERROR",
    SET_MARITAL_STATUS_ERROR: "SET_MARITAL_STATUS_ERROR",
    SET_HOME_ADDRESS_ERROR: "SET_HOME_ADDRESS_ERROR",
    SET_HOME_CONTACT_NO_ERROR: "SET_HOME_CONTACT_NO_ERROR",


    // Employee Save 
    REGISTER_EMP_REQUEST: "REGISTER_EMP_REQUEST",
    REGISTER_EMP_SUCCESS: "REGISTER_EMP_SUCCESS",
    REGISTER_EMP_ERROR: "REGISTER_EMP_ERROR"
}

export default actionTypes;